### PR TITLE
QA: Interior page revisions

### PR DESCRIPTION
**Pull request by benlk**
## Changes

This pull request makes the following changes:

- on pages, removes byline and date from template
- applies `clear: left` to left-aligned blocks on the IPBS template so they will no longer overlap
    ![Screen Shot 2020-02-05 at 13 49 39](https://user-images.githubusercontent.com/1754187/73872802-64779a00-481e-11ea-9b87-384dbabae00f.png)

- increases space between blocks on left and text on right from `1 * @measure` to `2 * @measure`
- adds the grey line at end of post content, above article prefooter
    ![Screen Shot 2020-02-05 at 13 44 35](https://user-images.githubusercontent.com/1754187/73872823-6e999880-481e-11ea-9836-0995b46d271c.png)

- when the sticky nav appears, adds padding to the top of the page so that the sticky nav does not cover up the post/page headline
    ![Screen Shot 2020-02-05 at 13 44 11](https://user-images.githubusercontent.com/1754187/73872838-7a855a80-481e-11ea-8177-78a2f40161e8.png)

- removes margin at the top of one of the primary container elements on the page, `#main`, so that the top of the page aligns with the bottom of the sticky nav
    ![Screen Shot 2020-02-05 at 13 51 21](https://user-images.githubusercontent.com/1754187/73872933-a0aafa80-481e-11ea-8719-95bb405dea53.png)


## Why

<!-- Why does this PR propose these changes? Take as much space as you need to explain. -->
<!-- If there are GitHub issues that this pull request addresses, please list them here. -->
For #35

## Testing/Questions

Features that this PR affects:

- pages with the IPBS template
- posts with the IPBS template
- the homepage, and really all pages
- mobile views

<!-- If there are no questions, please remove the questions section. -->
Questions that need to be answered before merging:

- [x] Is this PR targeting the correct branch in this repository?
- [ ] Do we want to make the gap wider?
- [ ] should the gap width vary in response to screen size?

Steps to test this PR:

1. no config changes necessary, just checkout.

<details>
<summary>sample post content for replication of the overlapping left-aligned blocks problem</summary>

```html
<!-- wp:paragraph -->
<p>This tests whether changes to single.php have broken the ability to choose the two-column default Largo template</p>
<!-- /wp:paragraph -->

<!-- wp:group {"backgroundColor":"darkblue","align":"full"} -->
<div class="wp-block-group alignfull has-darkblue-background-color has-background"><div class="wp-block-group__inner-container"><!-- wp:paragraph {"textColor":"white"} -->
<p class="has-text-color has-white-color">This paragraph block is in a full-width Group block.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p>Interdum et malesuada fames ac ante ipsum primis in faucibus.  Curabitur orci mauris, facilisis id auctor eu, tempus ut tortor. Etiam  tempor placerat turpis, sit amet ultricies mi auctor id.</p>
<!-- /wp:paragraph -->

<!-- wp:group {"backgroundColor":"darkred","align":"left"} -->
<div class="wp-block-group alignleft has-darkred-background-color has-background"><div class="wp-block-group__inner-container"><!-- wp:paragraph {"textColor":"white"} -->
<p class="has-text-color has-white-color">This paragraph block is in a left-aligned Group Block.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p>Suspendisse  pretium faucibus eros, eget consectetur dui ultricies ultricies.  Praesent condimentum nisl purus, in imperdiet quam lacinia a. Donec  suscipit ornare quam, sed lacinia ligula rutrum imperdiet. Integer  bibendum est ac erat gravida, at ornare diam efficitur. Integer gravida  felis et erat molestie pulvinar. Fusce non massa ac nisl feugiat varius.  Sed viverra maximus elit, suscipit tincidunt dui egestas pretium. Morbi  faucibus ante non odio placerat dictum. Sed in pulvinar nibh, sed  placerat quam. Proin scelerisque faucibus elit at tincidunt. </p>
<!-- /wp:paragraph -->

<!-- wp:group {"backgroundColor":"darkgreen"} -->
<div class="wp-block-group has-darkgreen-background-color has-background"><div class="wp-block-group__inner-container"><!-- wp:paragraph {"textColor":"white"} -->
<p class="has-text-color has-white-color">This Paragraph block is in an unaligned Group block.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p>
Duis eget tellus mauris. Vestibulum congue mi ac neque ultricies, sit 
amet tempus purus pellentesque. Suspendisse sagittis id lacus non 
varius. Pellentesque eget justo vel turpis blandit tempus. Aenean 
cursus, elit a luctus mattis, risus erat placerat sem, tempus 
sollicitudin augue mi eu tellus. Vestibulum pellentesque velit nisi, ut 
tincidunt neque mollis sed. Phasellus euismod mi ac erat porttitor, 
tempus tempus nunc malesuada.
</p>
<!-- /wp:paragraph -->

<!-- wp:group {"backgroundColor":"orange","align":"wide"} -->
<div class="wp-block-group alignwide has-orange-background-color has-background"><div class="wp-block-group__inner-container"><!-- wp:paragraph {"textColor":"white"} -->
<p class="has-text-color has-white-color">This Paragraph Block is in a wide-aligned Group block.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p> Donec enim metus, condimentum non molestie non, pulvinar a metus. Class  aptent taciti sociosqu ad litora torquent per conubia nostra, per  inceptos himenaeos. Donec ut lobortis neque, sed varius ligula. Nulla  facilisi. Morbi posuere mi dignissim est molestie, in convallis nisl  rutrum. Nulla augue quam, cursus vitae efficitur eget, placerat non  eros. Duis quam justo, aliquet non sapien ac, luctus condimentum libero.  Nulla facilisi. Nullam sollicitudin tempor auctor. Nam elementum  fermentum nunc quis hendrerit. Proin sollicitudin vestibulum sagittis.  Sed eget cursus est. Duis porta purus id nisl sodales sagittis. </p>
<!-- /wp:paragraph -->

<!-- wp:heading -->
<h2>Replication test for overlapping blocks.</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>First, a paragraph.</p>
<!-- /wp:paragraph -->

<!-- wp:group {"backgroundColor":"darkred","align":"left"} -->
<div class="wp-block-group alignleft has-darkred-background-color has-background"><div class="wp-block-group__inner-container"><!-- wp:paragraph {"textColor":"white"} -->
<p class="has-text-color has-white-color">This paragraph block is in a left-aligned Group Block. Phasellus fermentum diam  sed tincidunt pharetra. Nulla porta ante ligula, ac pulvinar orci  laoreet in. Donec quis congue eros. Aenean auctor condimentum velit  dictum pulvinar. Interdum et malesuada fames ac ante ipsum primis in  faucibus. Sed efficitur ante non vestibulum molestie. Curabitur  imperdiet arcu tellus, non tempor leo tristique sit amet. Etiam  convallis ante et est pretium, finibus dapibus mauris sollicitudin. Nunc  ac turpis non justo ultrices condimentum. Sed ornare dictum turpis,  vitae hendrerit urna maximus non. Mauris laoreet venenatis enim ac  laoreet. Fusce augue lorem, finibus eu lacus quis, aliquet ornare elit.  Curabitur feugiat porta posuere. </p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>List item 1</li><li>List item 2</li><li>List Item 3</li><li>List item 4</li></ul>
<!-- /wp:list --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p> The first left-aligned block comes before this paragraph. Proin porta neque et magna tincidunt finibus. Phasellus fermentum diam  sed tincidunt pharetra. Nulla porta ante ligula, ac pulvinar orci  laoreet in. Donec quis congue eros. Aenean auctor condimentum velit  dictum pulvinar. Interdum et malesuada fames ac ante ipsum primis in  faucibus. Sed efficitur ante non vestibulum molestie. Curabitur  imperdiet arcu tellus, non tempor leo tristique sit amet. Etiam  convallis ante et est pretium, finibus dapibus mauris sollicitudin. Nunc  ac turpis non justo ultrices condimentum. Sed ornare dictum turpis,  vitae hendrerit urna maximus non. Mauris laoreet venenatis enim ac  laoreet. Fusce augue lorem, finibus eu lacus quis, aliquet ornare elit.  Curabitur feugiat porta posuere. </p>
<!-- /wp:paragraph -->

<!-- wp:group {"backgroundColor":"darkred","align":"left"} -->
<div class="wp-block-group alignleft has-darkred-background-color has-background"><div class="wp-block-group__inner-container"><!-- wp:paragraph {"textColor":"white"} -->
<p class="has-text-color has-white-color">This paragraph block is in a left-aligned Group Block. Phasellus fermentum diam  sed tincidunt pharetra. Nulla porta ante ligula, ac pulvinar orci  laoreet in. Donec quis congue eros. Aenean auctor condimentum velit  dictum pulvinar. Interdum et malesuada fames ac ante ipsum primis in  faucibus. Sed efficitur ante non vestibulum molestie. Curabitur  imperdiet arcu tellus, non tempor leo tristique sit amet. Etiam  convallis ante et est pretium, finibus dapibus mauris sollicitudin. Nunc  ac turpis non justo ultrices condimentum. Sed ornare dictum turpis,  vitae hendrerit urna maximus non. Mauris laoreet venenatis enim ac  laoreet. Fusce augue lorem, finibus eu lacus quis, aliquet ornare elit.  Curabitur feugiat porta posuere. </p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><li>List item 1</li><li>List item 2</li><li>List Item 3</li><li>List item 4</li></ul>
<!-- /wp:list --></div></div>
<!-- /wp:group -->

<!-- wp:paragraph -->
<p> The second left-aligned block is floated left from immediately before this paragraph. Note that the second left-aligned block's position on the page is much after this block.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>Maecenas vitae dignissim eros. Maecenas tincidunt, tellus eget  consectetur fermentum, velit arcu venenatis mi, ac finibus tortor magna  et metus. Sed ut velit sit amet nisl rutrum dapibus in quis sem.  Phasellus sagittis felis eget augue condimentum, sed porttitor nunc  vehicula. Nunc scelerisque lobortis lectus, nec tincidunt lacus iaculis  ac. Nullam vitae libero sit amet purus tempus dignissim. Cras in ex eu  tellus molestie iaculis commodo et nunc. In auctor quam enim, vel  volutpat erat facilisis eget. Maecenas porttitor tellus quis turpis  rhoncus, et pharetra tortor rhoncus. Ut quis odio sit amet sapien porta  lacinia a eu purus. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>
Maecenas vitae dignissim eros. Maecenas tincidunt, tellus eget 
consectetur fermentum, velit arcu venenatis mi, ac finibus tortor magna 
et metus. Sed ut velit sit amet nisl rutrum dapibus in quis sem. 
Phasellus sagittis felis eget augue condimentum, sed porttitor nunc 
vehicula. Nunc scelerisque lobortis lectus, nec tincidunt lacus iaculis 
ac. Nullam vitae libero sit amet purus tempus dignissim. Cras in ex eu 
tellus molestie iaculis commodo et nunc. In auctor quam enim, vel 
volutpat erat facilisis eget. Maecenas porttitor tellus quis turpis 
rhoncus, et pharetra tortor rhoncus. Ut quis odio sit amet sapien porta 
lacinia a eu purus.
</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>
Maecenas vitae dignissim eros. Maecenas tincidunt, tellus eget 
consectetur fermentum, velit arcu venenatis mi, ac finibus tortor magna 
et metus. Sed ut velit sit amet nisl rutrum dapibus in quis sem. 
Phasellus sagittis felis eget augue condimentum, sed porttitor nunc 
vehicula. Nunc scelerisque lobortis lectus, nec tincidunt lacus iaculis 
ac. Nullam vitae libero sit amet purus tempus dignissim. Cras in ex eu 
tellus molestie iaculis commodo et nunc. In auctor quam enim, vel 
volutpat erat facilisis eget. Maecenas porttitor tellus quis turpis 
rhoncus, et pharetra tortor rhoncus. Ut quis odio sit amet sapien porta 
lacinia a eu purus.
</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>
Maecenas vitae dignissim eros. Maecenas tincidunt, tellus eget 
consectetur fermentum, velit arcu venenatis mi, ac finibus tortor magna 
et metus. Sed ut velit sit amet nisl rutrum dapibus in quis sem. 
Phasellus sagittis felis eget augue condimentum, sed porttitor nunc 
vehicula. Nunc scelerisque lobortis lectus, nec tincidunt lacus iaculis 
ac. Nullam vitae libero sit amet purus tempus dignissim. Cras in ex eu 
tellus molestie iaculis commodo et nunc. In auctor quam enim, vel 
volutpat erat facilisis eget. Maecenas porttitor tellus quis turpis 
rhoncus, et pharetra tortor rhoncus. Ut quis odio sit amet sapien porta 
lacinia a eu purus.
</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>
Maecenas vitae dignissim eros. Maecenas tincidunt, tellus eget 
consectetur fermentum, velit arcu venenatis mi, ac finibus tortor magna 
et metus. Sed ut velit sit amet nisl rutrum dapibus in quis sem. 
Phasellus sagittis felis eget augue condimentum, sed porttitor nunc 
vehicula. Nunc scelerisque lobortis lectus, nec tincidunt lacus iaculis 
ac. Nullam vitae libero sit amet purus tempus dignissim. Cras in ex eu 
tellus molestie iaculis commodo et nunc. In auctor quam enim, vel 
volutpat erat facilisis eget. Maecenas porttitor tellus quis turpis 
rhoncus, et pharetra tortor rhoncus. Ut quis odio sit amet sapien porta 
lacinia a eu purus.
</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>
Maecenas vitae dignissim eros. Maecenas tincidunt, tellus eget 
consectetur fermentum, velit arcu venenatis mi, ac finibus tortor magna 
et metus. Sed ut velit sit amet nisl rutrum dapibus in quis sem. 
Phasellus sagittis felis eget augue condimentum, sed porttitor nunc 
vehicula. Nunc scelerisque lobortis lectus, nec tincidunt lacus iaculis 
ac. Nullam vitae libero sit amet purus tempus dignissim. Cras in ex eu 
tellus molestie iaculis commodo et nunc. In auctor quam enim, vel 
volutpat erat facilisis eget. Maecenas porttitor tellus quis turpis 
rhoncus, et pharetra tortor rhoncus. Ut quis odio sit amet sapien porta 
lacinia a eu purus.
</p>
<!-- /wp:paragraph -->
```

</details>

### CODE REVIEW

**Comment by joshdarby** [comment]
Should we add more spacing between the post content and the `article-bottom` widget area?

Screen Shot 2020-02-05 at 2 27 10 PM

**Comment by joshdarby** [comment]
Other than the above question, I think this is good. 👍

**Comment by benlk** [comment]
There's some work in this PR regarding the navbar height that will need to be adjusted after #83 is merged.

**Comment by benlk** [comment]
> Should we add more spacing between the post content and the `article-bottom` widget area?

Can you recheck the whitespace, please? On posts I see sufficient whitespace before the article-bottom widget area:

Screen Shot 2020-02-05 at 17 34 58

**Comment by joshdarby** [comment]
Yep, I see that now on another post. I must have done something weird on the one above.

**Review by joshdarby — APPROVED** [review]

**Pull request merged**
